<?php

namespace ramshresh\yii2\galleryManager;

use Yii;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\helpers\Url;

/**
 * This is the model class for table "gallery_image".
 *
 * @property integer $id
 * @property string $type
 * @property string $ownerId
 * @property integer $rank
 * @property string $name
 * @property string $description
 *
 * @property string $src
 */
class GalleryImageAr extends \yii\db\ActiveRecord
{
    protected $galleryBehavior;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'gallery_image';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ownerId'], 'required'],
            [['rank'], 'integer'],
            [['rank','latitude','longitude'], 'number'],
            [['description','route'], 'string'],
            [['type', 'ownerId', 'name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'type' => Yii::t('app', 'Type'),
            'ownerId' => Yii::t('app', 'Owner ID'),
            'rank' => Yii::t('app', 'Rank'),
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
            'latitude' => Yii::t('app', 'Latitude'),
            'longitude' => Yii::t('app', 'Longitude'),
            'route'=>'Route',
        ];
    }
     /**
     * @param string $version
     *
     * @return string
     */
    public function getUrl($version)
    {
        return $this->galleryBehavior->getUrl($this->id, $version);
    }

    public function setGalleryBehavior($galleryBehavior){
        $this->galleryBehavior=$galleryBehavior;
    }


    public function attributes()
    {
        return ArrayHelper::merge(
            parent::attributes(),
            [
                'src',
            ]
        ); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->setAttribute('src',$this->getSrc('medium'));
    }

    public function beforeSave($insert)
    {
        if(parent::beforeSave($insert)){
             if($this->galleryBehavior){
                 /**
                  * @var $galleryBehavior \ramshresh\yii2\galleryManager\GalleryBehavior
                  */
                 $galleryBehavior = $this->galleryBehavior;
                 $versionsName = array_keys($galleryBehavior->versions);
                 $this->versions=new Expression("(select '".Json::encode($versionsName)."'::JSON)");
                 $this->route = $galleryBehavior->route;
                 $this->extension = $galleryBehavior->extension;
             }
        }
        return true;// TODO: Change the autogenerated stub
    }

    public function getSrc($version){
        return Url::to([$this->route]).'/'.$this->ownerId.'/'.$this->id.'/'.$version.'.'.$this->extension;
    }
}